name: tf2
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.1.0=gpu
  - absl-py=0.9.0=py37_0
  - albumentations=0.4.6=py_0
  - argon2-cffi=20.1.0=py37he774522_1
  - astor=0.8.0=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.5=py_0
  - blinker=1.4=py37_0
  - brotlipy=0.7.0=py37he774522_1000
  - ca-certificates=2020.7.22=0
  - cachetools=4.1.1=py_0
  - certifi=2020.6.20=py37_0
  - cffi=1.14.0=py37h7a1dbc1_0
  - chardet=3.0.4=py37_1003
  - click=7.1.2=py_0
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.3=py_0
  - cryptography=2.9.2=py37h7a1dbc1_0
  - cudatoolkit=10.1.243=h74a9793_0
  - cudnn=7.6.5=cuda10.1_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.10.1=py37he774522_0
  - dask-core=2.25.0=py_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - freetype=2.10.2=hd328e21_0
  - gast=0.2.2=py37_0
  - geos=3.8.0=h33f27b4_0
  - google-auth=1.20.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - graphviz=2.38=hfd603c8_2
  - grpcio=1.27.2=py37h351948d_0
  - h5py=2.10.0=py37h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=64.2=he025d50_1
  - idna=2.10=py_0
  - imageio=2.9.0=py_0
  - imgaug=0.4.0=py_1
  - importlib-metadata=1.7.0=py37_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2020.1=216
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.17.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.15.2=py37_0
  - jinja2=2.11.2=py_0
  - jpeg=9d=he774522_0
  - jsonschema=3.2.0=py37_1
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.6=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_contrib_nbextensions=0.5.1=py37_0
  - jupyter_core=4.6.3=py37_0
  - jupyter_highlight_selected_word=0.2.0=py37_1000
  - jupyter_latex_envs=1.4.4=py37_1000
  - jupyter_nbextensions_configurator=0.4.1=py37hc8dfbb8_1
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.2.0=py37h74a9793_0
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libclang=9.0.1=default_hf44288c_0
  - libiconv=1.15=vc14h29686d3_5
  - liblapack=3.8.0=14_mkl
  - liblapacke=3.8.0=14_mkl
  - libopencv=4.4.0=py37_2
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.12.3=h7bd577a_0
  - libsodium=1.0.18=h62dcd97_0
  - libtiff=4.1.0=h56a325e_1
  - libwebp-base=1.1.0=he774522_3
  - libxml2=2.9.10=h5d81f1c_2
  - libxslt=1.1.33=h579f668_1
  - lxml=4.5.2=py37h8ba8a40_0
  - lz4-c=1.9.2=h62dcd97_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.1.1=py37_0
  - markupsafe=1.1.1=py37hfa6e2cd_1
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py37h64f37c6_0
  - mistune=0.8.4=py37hfa6e2cd_1001
  - mkl=2019.4=245
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.1.0=py37h45dec08_0
  - mkl_random=1.0.4=py37h343c172_0
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.6.1=py37_1
  - nbformat=5.0.7=py_0
  - notebook=6.1.1=py37_0
  - numpy=1.19.1=py37h5510c5b_0
  - numpy-base=1.19.1=py37ha3acd2a_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py37_0
  - opencv=4.4.0=py37_2
  - openssl=1.1.1g=he774522_1
  - opt_einsum=3.1.0=py_0
  - packaging=20.4=py_0
  - pandas=1.1.0=py37ha925a31_0
  - pandoc=2.10=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.5.2=py_0
  - pickleshare=0.7.5=py37_1001
  - pillow=7.2.0=py37hcc1f983_0
  - pip=20.2.2=py37_0
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.5=py_0
  - prompt_toolkit=3.0.5=0
  - protobuf=3.12.3=py37h33f27b4_0
  - py-opencv=4.4.0=py37h43977f1_2
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_2
  - pydot=1.4.1=py37_0
  - pygments=2.6.1=py_0
  - pyjwt=1.7.1=py37_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.12.3=py37h6538335_1
  - pyreadline=2.1=py37_1
  - pyrsistent=0.16.0=py37he774522_0
  - pysocks=1.7.1=py37_1
  - python=3.7.7=h81c818b_4
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=py_0
  - pywavelets=1.1.1=py37he774522_0
  - pywin32=227=py37he774522_1
  - pywinpty=0.5.7=py37_0
  - pyyaml=5.1.2=py37hfa6e2cd_0
  - pyzmq=19.0.1=py37ha925a31_1
  - qt=5.12.5=h7ef1ec2_0
  - qtconsole=4.7.5=py_0
  - qtpy=1.9.0=py_0
  - requests=2.24.0=py_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.6=py_0
  - scipy=1.5.0=py37h9439919_0
  - send2trash=1.5.0=py37_0
  - setuptools=49.3.1=py37_0
  - shapely=1.7.1=py37h210f175_0
  - sip=4.19.23=py37ha925a31_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=h2a8f88b_0
  - tensorboard=2.2.1=pyh532a8cf_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.1.0=gpu_py37h7db9008_0
  - tensorflow-base=2.1.0=gpu_py37h55f5790_0
  - tensorflow-estimator=2.1.0=pyhd54b08b_0
  - tensorflow-gpu=2.1.0=h0d30ee6_0
  - termcolor=1.1.0=py37_1
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=he774522_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py37he774522_1
  - tqdm=4.48.2=py_0
  - traitlets=4.3.3=py37_0
  - urllib3=1.25.10=py_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.14.1=py37_0
  - wheel=0.34.2=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - wrapt=1.12.1=py37he774522_1
  - xz=5.2.5=h62dcd97_0
  - yaml=0.1.7=vc14h4cb57cf_1
  - zeromq=4.3.2=ha925a31_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=vc14h1cdd9ab_1
  - zstd=1.4.4=ha9fde0e_3
  - pip:
    - efficientnet==1.0.0
    - image-classifiers==1.0.0
    - networkx==2.4
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - scikit-image==0.17.2
    - segmentation-models==1.0.1
    - tifffile==2020.7.24
prefix: C:\Users\RAJDEEP\Anaconda\Anaconda3\envs\tf2
